export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_PENDING = "FETCH_POST_PENDING";
export const FETCH_POST_FULFILLED = "FETCH_POST_FULFILLED";
export const FETCH_POST_REJECTED = "FETCH_POST_REJECTED";
